### PR TITLE
Add tui feature to allow building without ncurses

### PR DESCRIPTION
**Pull request by ivy**
This PR makes ncurses an optional dependency.

### CODE REVIEW

**Comment by ivy** [comment]
Is this PR okay to merge? Making the TUI an optional dependency really helps us slim down the build. Especially in the case of large-scale deploys where interactive features aren't necessary.

**Comment by yeastplume** [comment]
Sure, sorry I've missed this. Looks good, and agree with making TUI optional. Will review properly and merge once T4 is in place (just want to minimise changes until then)

**Comment by illera88** [comment]
This is actually pretty helpful. 
Thanks @ivy

**Comment by illera88** [comment]
@yeastplume can you please merge this PR? 

Offtopic-ish: what do you think about changing the `Cursive` [backend](https://github.com/gyscos/Cursive/wiki/Backends) to `termion-backend` so there is no extra dependencies (`ncurses`) to the miner (same thing applies to `Grin`)?

Cheers

**Comment by yeastplume** [comment]
Looks fine, but there are still merge conflicts

**Pull request closed without merging**
