### PR TITLE
Nicehash protocol modifications

### PR DESCRIPTION
**Pull request by gingertrol**
Added were parameters: xn and cleanjob in job method. These parameters are defined in Nicehash specifications:
https://github.com/nicehash/Specifications/blob/master/Grin_NiceHash_v1.0.txt

Other incompatibility fixes:
- Parameter job id was changed from u32 to u64.
- Request detection was changed. The job request is the only request that can be sent from the stratum server.

### CODE REVIEW

**Comment by yeastplume** [comment]
This breaks all compatibility. What is the goal here? Where did this specification come from? Was there a discussion I missed?

**Comment by gingertrol** [comment]
Compatibility issues are fixed.

Grin "stratum" specification is poorly designed and there are missing functionalities that are de facto standard in mining protocols for other algorithm and used for years. Nicehash added that missing pieces in its own specification to upgrade existing grin mining protocol and that enables Nicehash platform to function properly with grin protocol. There was nothing new invented only added what was missing.  
We believe that pools will soon adapt our changes, to avoid duplicate shares, as mining communitiy will grow and the number of miners will increase.

**Comment by bladedoyle** [comment]
The original "stratum" implementation was purposefully "minimal" and was not intended to have full functionality.  Ref:
https://github.com/mimblewimble/grin/issues/935#issuecomment-379097938
```
I wouldn't be opposed to a minimal stratum-like server embedded in grin
```

I see the following changed proposed by your PR:
1) change job_id from u32 to u64.   I cant imagine any circumstance where we would need that many versions of a job with a 1-minute block interval. 
2) Add xn (extranonce?) field.  It isnt clear to me whay this is necessary for grin since there is really no chance of overflowing the existing nonce range (per discussions with Tromp).  It isnt clear there is any value to adding extranonce to the protocol if the block header does not support it.
3) Add "cleanjob".  I suppose it could be useful to ask the miner to stop mining though I cant think of any obvious reasons.
4) Fix the test for response/request.  This change seems ok.

**Comment by gingertrol** [comment]
I agree with you that the original stratum is not the best protocol and it could be more optimized, but the way miners and pools are working nowadays, grin spec doesn't fulfill the need of mining community. Like Einstein said:  "Make everything as simple as possible, but not simpler."

Three messages are all you need for mining protocol and that is: login, notify, submit with appropriate fields to satisfy all needs for mining. This is even simpler that grin specification.

1. In other stratum protocols, job_id is hex_string. Nicehash system generates for each job unique job id which is unique across all miners connected at the given moment. That way it can easily separate the jobs between miners. Internally it is u64 because we have a lot of users and many jobs are sent to each of them. For me, job_id depends on pool implementation detail and not to the blockchain feature. 
2. Most mining protocols are defined that way, that part of the nonce is specified by a pool. Original stratum defines extranonce1. Grin is defined that way that nonce size is fixed to 8 bytes. xn defines N most significant bytes of the nonce, the rest is chosen by a miner. In Nicehash system 2 bytes are defined and submitted to a miner. The reason behind is sharing the work among several miners to reduce the chance of two miner doing the same job with the same nonce. About some time ago sha256 pools introduced Asic-boost extension of stratum protocol which added the third parameter that was chosen by the pool to reduce share duplicates and reports say the profit of pools increased for 20% using that extension.
3. In grin stratum protocol it is defined that when miner receives job_id = 0 it should interrupt current job and replace the current job with this one after the current graph is complete. If I saw correctly in grin miner code this is not implemented, instead, the height of the block is checked. Either of these two approaches doesn't go well on Nicehash system. Job_id is an implementation detail and a lot of "submit" messages with job_id with 0 would generate confusion to which actual job or even miner it belongs. The problem with hight is that in our system there can be several jobs with the same height, and when switching job on a miner it wouldn't stop mining the previous job. So this why additional parameter like clean_job is needed to tell miner to stop the job and start with the new one.

**Comment by ignopeverell** [comment]
1. Nothing against using a `u64` from me as long as it's backward compatible. Pools can decide to use the extra space or not.
2. It's sometimes hard to wrap your head around the space given by a `u64`. This is an example of the birthday problem so it's straightforward to approximate. Future-proofing a bit, the probability of collision with 1M workers each randomizing their nonce and mining at 100 GPS is around 0.0163% for each block. So 2 workers over 1M could overlap for a minute on average every 6000 blocks or over 4 days. Is that something you're very worried about?
3. No objection to `clean_job` as long as it's backward compatible (miner will switch on a new height OR a clean_job passed as true).

No appetite for a `reconnect` message? Also, this should be matched with a PR on the stratum server.

**Pull request closed without merging**
